# Generated by Django 5.1.2 on 2024-10-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
