# Generated by Django 5.1.2 on 2024-10-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_articles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='cover',
            field=models.ImageField(default='', upload_to='images/post'),
            preserve_default=False,
        ),
    ]
