# Generated by Django 5.1.2 on 2024-10-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articles_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cover',
            field=models.ImageField(upload_to='news/images/post'),
        ),
    ]
